spring:
  application:
    name: tickets-api
  datasource:
    url: jdbc:mysql://localhost:3306/uifce_support?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #hibernate:
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        serialization-mode: via_dto


